require_relative 'support/ship_behaviors'
require_relative '../sinkable'
require_relative '../ship.rb'
require_relative '../carrier'
require_relative '../battleship'
require_relative '../cruiser'
require_relative '../submarine'
require_relative '../destroyer'
